version: '3'
services:
    ui:
        build:
            context: ui
            dockerfile: Dockerfile.prod 
        restart: on-failure:5
        networks:
            - traefik
        labels:
            # traefik config
           - "holten.publish=j"
           - "traefik.http.routers.ui.rule=Host(`hirsch.holten.de`)"
           - "traefik.http.routers.ui.tls.certResolver=letsencrypt"

networks:
    traefik:
        external: true
